version: '3'
services:
  compfestbin:
    build: src/app
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "1.00"
          memory: 800M
      restart_policy:
        condition: on-failure
    networks:
      - compfestbin-network
      
  nginx:
    image: nginx:alpine
    restart: on-failure
    ports:
      - 12021:80
    networks:
      - compfestbin-network
    volumes:
      - ./src/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  compfestbin-network:
    ipam:
      driver: default
      config:
        - subnet: 172.31.53.0/24